### PR TITLE
Remove broken map on index page

### PR DESCRIPTION
**Pull request by Jenselme**

### CODE REVIEW

**Comment by jmckenna** [comment]
i've been maintaining this map, please let me know when it is broken.  Most times it means demo.mapserver.org was down (which it isn't now).  Sad to see it removed actually.  But one less task for me :)

**Comment by jmckenna** [comment]
can you define "broken"?  It is based on tiles that live on demo.mapserver.org  I always make sure it is working.

Anyway, like I said, one less task for me.

**Comment by jmckenna** [comment]
Possibly one could argue that the map tiles need updating (change extents, such as to FOSS4G 2016 extents).  But as for broken, I was maintaining it.

Anyway, carry on.

**Comment by jmckenna** [comment]
I can bet what was happening is that the map wasn't showing on your local copy of the docs, but in fact it works on the live server (this has existed for about 5 years for me).

**Comment by dmorissette** [comment]
The map links to a mapcache install that is not currently working, even on the live site:

http://demo.mapserver.org/geocache/tms1.0.0/osm-denver@osmgrid/8/19/13.png

```
Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.2.16 (Debian) Server at demo.mapserver.org Port 80
```

**Comment by jmckenna** [comment]
Thanks for reporting this Daniel.  Fixed.  This happens sometimes when the machine is rebooted.

Please add the map back to the page.

**Comment by jmckenna** [comment]
i've also now added a monitoring service for that link.  Thanks for reporting this.

**Pull request merged**
