### PR TITLE
Update wfs_server.txt

### PR DESCRIPTION
**Pull request by ShivamRai2003**
The following link is broken. no such host is there.
so removed this  link :-http://ogc.dmsolutions.ca

### CODE REVIEW

**Comment by dmorissette** [comment]
Almost there. Need to also remove the "See"  on the line above.  :-)

**Comment by ShivamRai2003** [comment]
Done! Please Merge

**Comment by dmorissette** [comment]
Looks good now. Thanks!  I will leave the honor to your mentor to do the final review and merge the PR since I don't want to interfere with the process already in place.

**Comment by ShivamRai2003** [comment]
> Looks good now. Thanks! I will leave the honor to your mentor to do the final review and merge the PR since I don't want to interfere with the process already in place.

Thanks @dmorissette  for your comments!

**Comment by jmckenna** [comment]
Thanks for the review @dmorissette .  Thanks for the correction @ShivamRai2003

**Comment by ShivamRai2003** [comment]
@jmckenna Thanks!

**Pull request merged**
