### PR TITLE
Removing broken link :- http://tinyows.org/trac/wiki/LibxmlSchemaGmlBug

### PR DESCRIPTION
**Pull request by ShivamRai2003**
After going through a long documentation. i notice that this link  has no connection.
so please remove this link :- http://tinyows.org/trac/wiki/LibxmlSchemaGmlBug

### CODE REVIEW

**Comment by ShivamRai2003** [comment]
@jmckenna Please Review It!
Thanks

**Comment by jmckenna** [comment]
please STOP editing these very old RFP (proposal) documents and focus your/my efforts on the rest of the documentation.

**Comment by jmckenna** [comment]
Please also STOP using exclamation marks (!!!) to conversations with the community.  Community members are volunteers.   If you are not respectful inside a FOSS community, you will not get the help that you need.

**Comment by jmckenna** [comment]
thanks @ShivamRai2003

**Pull request merged**
