### PR TITLE
Add new Makefile options

### PR DESCRIPTION
**Pull request by yjacolin**
Add some options to makefile, w/o descriptions

### CODE REVIEW

**Comment by yjacolin** [comment]
I didn't find any information about what WITH_POSTGRESQL options needs (libpq? Which dir for standard installation on Debian). I could improve more if you can give the information. :)

**Comment by jmckenna** [comment]
@yjacolin I think these changes should be made against master, not branch-7-4

**Comment by jmckenna** [comment]
oh sorry, please ignore my last comment.   (I didn't realize this is docs, ha!)

**Comment by yjacolin** [comment]
@jmckenna yes different workflows are confusing

**Comment by jbo-ads** [comment]
PosgreSQL is needed for [second level dimensions](https://mapserver.org/mapcache/dimensions.html#postgresql-dimensions) as a dimension backend. It is used in [lib/dimension_pg.c](https://github.com/mapserver/mapcache/blob/master/lib/dimension_pg.c) source file. _libpq_ and _libpq_fe.h_ are needed when this feature is enabled.

**Pull request merged**
