### PR TITLE
Added some definitions for COMPOP options

### PR DESCRIPTION
**Pull request by tchaddad**

### CODE REVIEW

**Comment by yjacolin** [comment]
Great addition! Thanks!

**Comment by havatv** [comment]
Great contribution, indeed.
There are some issues with the formatting (too long lines, and wrong indent for the first line - "- clear"), but I can merge it and fix the issues later.

**Comment by havatv** [comment]
Formatting fixed with a36c365.

**Comment by tchaddad** [comment]
Apologies about the formatting - I think it got messed up because I submitted via the GitHub interface. Was ok in Sphinx on my local machine.

I also created sample images and posted them here:
https://github.com/tchaddad/mscomposite

Put them in that location mainly because I wasn't sure of the best way to link them to the page, or otherwise provide the image samples. If you think they would be useful, and have a suggestion how best to do it, I'm happy to attempt to add them.

**Comment by tchaddad** [comment]
An example image:

https://github.com/tchaddad/mscomposite/blob/master/testimages/test_color-burn.png

**Comment by sdlime** [comment]
Agreed, these are awesome. A picture is really helpful in this case. --Steve

**Comment by tchaddad** [comment]
We could make a smaller set that is more thumbnail size too. 

I originally wondered if it would work as a table containing the definitions, and just having a column for the resulting thumbnails. Wasn't sure if the docs used tables elsewhere?

**Comment by jmckenna** [comment]
Wonderful work @tchaddad thank you!!

Although I like @havatv's idea of a new examples page, I would prefer including them inline on the same composite.txt page, in a table of definitions and thumbnails as @tchaddad suggested.   Actually the bottom of the MS4W download page (also restructured text) does this in a table of thumbnails;  I use a "list-table" for that http://docutils.sourceforge.net/docs/ref/rst/directives.html#list-table

But this needs experimentation.  @tchaddad can you try a table on the same page with thumbnails and see how it looks?  If it gets too crazy then start a separate composite_examples.txt page       Sound good??

**Comment by jmckenna** [comment]
snippet of my list-table syntax used:

```
.. list-table:: List of MS4W Applications
   :widths: 1,1,1,40
   :header-rows: 1

   * - Application
     - File
     - Size
     - Screen Capture
   * - GeoMOOSE
     - `geomoose-3.2.0-ms4w.zip <https://ms4w.com/release/apps/geomoose-3.2.0-ms4w.zip>`__
     - 31 MB
     -  .. image:: images/geomoose3.png
           :scale: 25 %
           :alt: GeoMOOSE3 demo interface           
   * - Mapbender
     - `mapbender_3.0.6.3_ms4w.zip <https://ms4w.com/release/apps/mapbender_3.0.6.3_ms4w.zip>`__
     - 80 MB
     -  .. image:: images/mapbender.png
           :scale: 25 %
           :alt: Mapbender demo interface
```

**Comment by tchaddad** [comment]
thanks Jeff - I will give that a try and get back to you!

**Pull request merged**
