### PR TITLE
Updated OpenGeospatial Link

### PR DESCRIPTION
**Pull request by ShivamRai2003**
Hi Guys This link is no longer exist. Not found Error 403 
Link is this :- http://www.opengeospatial.org/functional/?page=swe
So I have removed the older one and added the correct.
Here is the corrected link :-https://www.opengeospatial.org/projects/initiatives/swe_rfi

### CODE REVIEW

**Comment by ShivamRai2003** [comment]
@jmckenna Done! Please Review

**Comment by ShivamRai2003** [comment]
Done @jmckenna

**Comment by jmckenna** [comment]
Please google "ogc swe" for the link.

**Comment by ShivamRai2003** [comment]
i have done that and found that only @jmckenna

**Comment by ShivamRai2003** [comment]
or you are talking about this http://www.opengeospatial.org/domain/swe

**Comment by jmckenna** [comment]
Second idea.  By the way, again, all this effort should not go into these very old RFC (proposal) documents, and instead into the other sections of the website.

**Comment by ShivamRai2003** [comment]
I think This is fine @jmckenna

**Comment by jmckenna** [comment]
It is not.  That is not the last one you proposed.

**Comment by jmckenna** [comment]
Slow down, take a breath, you will do better quality (the mentors and admins have been trying to teach you this, unsuccessfully).

**Comment by jmckenna** [comment]
Please change the link to http://www.opengeospatial.org/domain/swe

**Comment by ShivamRai2003** [comment]
@jmckenna Do you know i have seen this link only in first but i guessed it's wrong.

**Comment by jmckenna** [comment]
This one is my mistake.  We should use this instead, sorry (notice https)  https://www.opengeospatial.org/domain/swe/

**Comment by ShivamRai2003** [comment]
Great! Appreciable

**Comment by jmckenna** [comment]
Thanks @ShivamRai2003    Now please do not focus anymore on RFC (proposal) documents, but instead on the other parts of the website.  Thanks again!

**Comment by ShivamRai2003** [comment]
Thanks @jmckenna . Ok I understand

**Pull request merged**
