### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by lubojr**
fixes a small typo in wcs_server.html

### CODE REVIEW

**Comment by lubojr** [comment]
Ah sorry, just noticed that translated pages are probably not to be updated. I updated a change only to the 'en' version.

**Comment by geographika** [comment]
@lubojr - thanks for this.

**Comment by geographika** [comment]
@lubojr - actually this pull request should be merged against the current active docs - branch-7-4
Could you also make the same pull request against this branch?

**Comment by lubojr** [comment]
@geographika Sorry for messing that up. Will do now.

**Pull request merged**
