### PR TITLE
Rewrite IIS MapServer configuration doc

### PR DESCRIPTION
**Pull request by geographika**
See #181

### CODE REVIEW

**Comment by jmckenna** [comment]
Thanks @geographika Nice work.  My comments are that the original author should still be listed as a co-author, even if it is rewritten.  And also MS4W should be listed in this as well, likely as a note or tip, as so many use MS4W with IIS on their servers.  I will add these small edits now..

**Comment by jmckenna** [comment]
@geographika can you also add the missing files "unblock_zip.png" and "windows_features.jpg" ?

**Comment by jmckenna** [comment]
you are right about removing the former author, as I see that it is a complete rewrite.    But please upload those 2 missing images. thanks!

**Comment by geographika** [comment]
@jmckenna - images added (to another pull request - not sure how to add them to this one). 

The ms4w docs refer back to this page - http://ms4w.com/README_INSTALL.html#o-installing-the-ms4w-mapserver-binaries-in-other-environments - and the original version included these details. However they were very out of date (user accounts don't exist anymore, all versions from 2005), and wouldn't work as written. You have updated notes at http://www.mapserver.org/installation/php.html - would it make sense to make this page a ms4w plus PHP setup page - and you have details for ms4w/IIS at http://www.mapserver.org/installation/php.html#example-steps-of-a-full-windows-installation

**Comment by jmckenna** [comment]
agreed, thanks for pushing MS4W, actually I'll tackle updating the docs for MS4W here after this next MS4W release.

**Pull request merged**
