### PR TITLE
Submit RFC 124 on MapServer SLD Improvements

### PR DESCRIPTION
**Pull request by jbo-ads**
This RFC proposes to address some issues on MapServer SLD support. This is currently a work in progress that will span over the year. Still, early comments will be highly appreciated.

### CODE REVIEW

**Comment by jmckenna** [comment]
Thanks Jerome!  (your RFC should be automatically visible on mapserver.org in about 15 minutes)

**Comment by jratike80** [comment]
I did read a mail about this from mapserver-dev mailing list some time ago but we do have also Mapserver users who might have something to say. I know that some of our clients have not been totally satisfied with the current status of GetStyles and SDL/SLD_BODY. I suggest to ask comments from mapserver-users list as well.

**Comment by jmckenna** [comment]
This was introduced today at the MapServer meeting during the code sprint.  The RFC draft is a good first step.

**Comment by jbo-ads** [comment]
Did I do something wrong? RFC 124 doesn't show up on documentation, at least on my computer.

**Comment by jmckenna** [comment]
You did nothing wrong.   Must be Travis issue etc.        Checking.....

**Comment by jmckenna** [comment]
I've triggered a test build on Travis (takes 15 min), let's see what happens.  For some reason your commit did not trigger the website auto-update, maybe it was just a glitch.  crossing fingers...

**Comment by jmckenna** [comment]
My lord, it took me all this time, Travis makes my brain hurt :)      For some reason (maybe since we switched branches) I had to add "make clean" into our Travis build script, for every triggered build.  Your RFC is finally visible!  :)

**Pull request merged**
