### PR TITLE
add commandline options to mapcache seeder documentation

### PR DESCRIPTION
**Pull request by andreassteiner97**
added missing commandline options to mapcache seeder documentation

### CODE REVIEW

**Comment by andreassteiner97** [comment]
sorry for the mistake :D just copied the text from the debian.org page :D

**Comment by jmckenna** [comment]
Looks good here

**Comment by jbo-ads** [comment]
Good to me as well.

**Comment by jmckenna** [comment]
thanks for the contrib @andreassteiner97 !!

**Pull request merged**
