### PR TITLE
Add another example to Symbol construction

### PR DESCRIPTION
**Pull request by havatv**
Showing the use of ANCHORPOINT in combination with rotation ANGLE and multiple features on locations.

### CODE REVIEW

**Comment by jmckenna** [comment]
@havatv just a small note that I recently battled the fact that all ~1000 pages of the PDF output from the docs contained all of the images and text misaligned all throughout the document....you can image how difficult it was for me to track down the cause of that with close to 1000 pages (I did this as part of the 7.6 release).  In the end I tracked it down to the Symbol Construction document & the same " | ...... | "code blocks as you have added through this PR (see https://github.com/mapserver/docs/commit/2085ac965d406107ac5957665273ff8eff90d030 ).   I personally would like to stick with regular mapfile codeblocks from now on, to save my grief of hours for the next release :)  

Thoughts?  Sorry for this comment, but it really sucked having to find this error in 1000 pages ha.

**Comment by havatv** [comment]
> @havatv just a small note that I recently battled the fact that all ~1000 pages of the PDF output from the docs contained all of the images and text misaligned all throughout the document....you can image how difficult it was for me to track down the cause of that with close to 1000 pages (I did this as part of the 7.6 release). In the end I tracked it down to the Symbol Construction document & the same " | ...... | "code blocks as you have added through this PR (see [2085ac9](https://github.com/mapserver/docs/commit/2085ac965d406107ac5957665273ff8eff90d030) ). I personally would like to stick with regular mapfile codeblocks from now on, to save my grief of hours for the next release :)
> 
> Thoughts? Sorry for this comment, but it really sucked having to find this error in 1000 pages ha.

Sorry about that @jmckenna. Are there other ways to get multi-column code blocks?
Using tables ("| |") results in quite nice HTML rendering. If there are no alternatives to "| |" tables, is there anything I can do to make sure that these tables are not causing trouble for the PDF rendering?

**Comment by jmckenna** [comment]
Yes good find @havatv that was likely exactly the cause.

**Comment by jmckenna** [comment]
I take back what I said about " |...| " as I agree it really helps the reader understand.

**Comment by jmckenna** [comment]
Thanks @havatv again.

**Comment by havatv** [comment]
> Thoughts? Sorry for this comment, but it really sucked having to find this error in 1000 pages ha.

If you need help tracking down issues with PDF rendering (especially those caused by my bad formatting habits), please let me know.

**Comment by jmckenna** [comment]
You do great, I was just worried it was those tables causing us grief.

**Pull request merged**
